"""updated items by order

Revision ID: 0ab442bccaa7
Revises: ff711231ee15
Create Date: 2023-12-03 16:42:57.569201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ab442bccaa7'
down_revision: Union[str, None] = 'ff711231ee15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsbyorder', sa.Column('item_barcode', sa.Integer(), nullable=True))
    op.drop_constraint('itemsbyorder_item_id_fkey', 'itemsbyorder', type_='foreignkey')
    op.create_foreign_key(None, 'itemsbyorder', 'items', ['item_barcode'], ['barcode'])
    op.drop_column('itemsbyorder', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsbyorder', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itemsbyorder', type_='foreignkey')
    op.create_foreign_key('itemsbyorder_item_id_fkey', 'itemsbyorder', 'items', ['item_id'], ['id'])
    op.drop_column('itemsbyorder', 'item_barcode')
    # ### end Alembic commands ###
