"""adding qty to items by order

Revision ID: c133171f7dd1
Revises: f9980866369b
Create Date: 2023-12-03 19:28:48.494046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c133171f7dd1'
down_revision: Union[str, None] = 'f9980866369b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsbyorder', sa.Column('qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemsbyorder', 'qty')
    # ### end Alembic commands ###
