"""updated itemsbyorder

Revision ID: f9980866369b
Revises: 0ab442bccaa7
Create Date: 2023-12-03 16:54:09.414951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9980866369b'
down_revision: Union[str, None] = '0ab442bccaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsbyorder', sa.Column('item_barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('itemsbyorder_item_id_fkey', 'itemsbyorder', type_='foreignkey')
    op.create_foreign_key(None, 'itemsbyorder', 'items', ['item_barcode'], ['barcode'])
    op.drop_column('itemsbyorder', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemsbyorder', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itemsbyorder', type_='foreignkey')
    op.create_foreign_key('itemsbyorder_item_id_fkey', 'itemsbyorder', 'items', ['item_id'], ['id'])
    op.drop_column('itemsbyorder', 'item_barcode')
    # ### end Alembic commands ###
