"""updated items barcode unique

Revision ID: ff711231ee15
Revises: 0a5b4a27f3dc
Create Date: 2023-12-03 16:42:02.137825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff711231ee15'
down_revision: Union[str, None] = '0a5b4a27f3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'items', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='unique')
    # ### end Alembic commands ###
