services:
  api:
    build: ./API
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./API:/app
    ports:
      - 8008:8000
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://fastapi_user:fastapi_password@db:5432/fastapi_eshop
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgress_data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_password
      - POSTGRES_DB=fastapi_eshop

volumes: 
  postgress_data: